[project]
name = "reddit-privacy"
version = "0.1.0"
description = "A personal project to improve my privacy on Reddit"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "praw>=7.8.1",
]
